Merged in JDCMT-203-measure-code-coverage-for-angular-tests (pull request #58)
JDCMT-203 measure code coverage for Angular tests

* JDCMT-203 collect code coverage for Angular tests

* JDCMT-203 fixed YAML syntax error

* JDCMT-203 resolved PR comments

* JDCMT-203 updated vulnerable package

* Merge branch 'master' into JDCMT-203-measure-code-coverage-for-angular-tests

# Conflicts:
#	bitbucket-pipelines.yml


Approved-by: Marek Parfianowicz
Approved-by: Volodymyr Batrukh

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -118,19 +118,23 @@ definitions:
           username: netrunners
           password: $PIPELINES_JWT_TOKEN
         script:
+          - rm -rf /var/lib/apt/lists/*
+          - export CHROME_BIN=/usr/bin/google-chrome
           - dotnet tool install --global dotnet-sonarscanner
           - dotnet tool install --global JetBrains.dotCover.GlobalTool
           - export PATH="$PATH:/root/.dotnet/tools"
-          - dotnet sonarscanner begin /k:"$SONAR_REPOSITORY" /d:sonar.host.url="$SONAR_URL"  /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.coverage.exclusions=src/**/ClientApp/**/*
+          - dotnet sonarscanner begin /k:"$SONAR_REPOSITORY" /d:sonar.host.url="$SONAR_URL"  /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.javascript.lcov.reportPaths=./ClientApp/coverage/lcov-report/lcov.info
           - dotnet build --no-incremental
           - dotnet dotcover test --dcReportType=HTML
+          - npm install --prefix ./src/MicrosoftTeamsIntegration.Jira/ClientApp
+          - npm run test:pipeline --no-sandbox --prefix ./src/MicrosoftTeamsIntegration.Jira/ClientApp
           - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
           - |
             ENCODED_BRANCH=$(echo "$BITBUCKET_BRANCH" | jq -sRr @uri)
             STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonar-enterprise.internal.atlassian.com/api/qualitygates/project_status?projectKey=msteams-jira-onprem&branch=$ENCODED_BRANCH" | jq -r .projectStatus.status)
             if [ "$STATUS" != "OK" ]; then
-               echo "Quality gate failed: https://sonar-enterprise.internal.atlassian.com/dashboard?id=msteams-jira-onprem&branch=$ENCODED_BRANCH"
-               exit 1
+              echo "Quality gate failed: https://sonar-enterprise.internal.atlassian.com/dashboard?id=msteams-jira-onprem&branch=$ENCODED_BRANCH&"
+              exit 1
             fi
 pipelines:
   default:
